### ISSUE TITLE
Unable to save images with default preferences in v2.2.0

### ISSUE THREAD

**Issue by AnonymFegis** [mcdamo/tab-image-saver#19]
I tried saving images from different sites, but the error message was the same.

Browser Console:
rule: <, filename: <, valid: false background.js:289:7
rule: n, filename: n, valid: true background.js:289:7
Error: "Invalid filename generated: images/n" background.js:516:19

**Comment by mcdamo** [comment]
This bug appears to be specific to when the addon is using the default preferences.
A workaround is to open the preferences and toggle any setting, this will trigger the preferences to be saved and the addon should work even after restarting the browser. 
An update to fix this bug will be provided soon.

**Comment by MirceaKitsune** [comment]
Confirming that upon changing a setting, the addon is working properly again. Thanks!

Note that I wasn't using the default preferences however: I had already changed some of the settings in the previous version since months ago, so it seems more accurate to say that it doesn't work when using the settings from a previous version.

**Comment by mcdamo** [comment]
This is resolved in v2.2.1
