### ISSUE TITLE
Path rules (image names and extensions) broken

### ISSUE THREAD

**Issue by modelfe** [mcdamo/tab-image-saver#75]
The latest update (4.0.0) has broken the downloaded image names. They're now all named

```
_name_._ext_
_name_(1)._ext_
_name_(2)._ext_
```

etc.

Tested on multiple sites. The images themselves still open fine, they just have the wrong name and extension.

Firefox 97.0.1
Linux Mint 20.3

**Comment by mcdamo** [comment]
Looks like you might need to [run the update](https://github.com/mcdamo/tab-image-saver-dev/blob/master/CHANGES-4.0.md)

**Comment by DocHobo** [comment]
I'm on 4.0.2 and it's still doing _name_.ext_

**Comment by mcdamo** [comment]
@DocHobo were you able to [run the update](https://github.com/mcdamo/tab-image-saver-dev/blob/master/CHANGES-4.0.md)?

**Comment by DocHobo** [comment]
that link just gives me a 404 because it has -dev in it so [here's a link for the public.](https://github.com/mcdamo/tab-image-saver/blob/master/CHANGES-4.0.md)  and now that I'm able to check the page I see what you mean by running the update.  I thought you just meant updating to 4.0, which is why I was confused since I was on 4.0.2, but I see I need to update my preferences, and yeah it works now. thanks for the help and sorry for the confusion
